[allinclusive]
atomserver ansible_host=31.134.151.220 ansible_port=10022


[allinclusive:vars]
# ansible_host=127.0.0.1
ansible_user=dmitrii
# ansible_private_key_file=.vagrant/machines/default/virtualbox/private_key
