# Common JIRA settings. You can't/mustn't put password here!
confluence:
  address:          https://iapi.merck.com/confluence/v1/
  user:             gusevdm

proxy:
  http: 127.0.0.1:3180
  https: 127.0.0.1:3180

# default output file (for reports)
output:
  file: jira_report.out
