# Configuration file for python GIT utility.
#
# Created: Gusev Dmitrii, 2017
# Modified: Gusev Dmitrii, 20.02.2017

# repositories storage for different systems
location:
  win:    c:/projects
  linux:  /home/gusevdm/projects
  macos:  /Users/gusevdmi/projects

# general stash settings
stash:
  address:  https://gusevdmi:{}@stash.merck.com/scm

#proxy:
#  http: 127.0.0.1:3180
#  https: 127.0.0.1:3180

# special settings for projects
mvn_settings: configs/msd-settings.xml

# list of repositories
repositories:
  bdp:  # BigData platform
    mantis:
      build: no
    mantis11:
      build: yes
    ingest-script-generator:
      build:  yes
    sqoop-msd:
      build:  no
    csv2abstract:
      build: yes
    csv2hive:
      build: yes
  man:  # Mantis
    mantis-bds:
      build: no
    mantis-pdc:
      build: no
    mantis-ops:
      build: no
    mantis-systems:
      build: yes
    mantis-teradata:
      build: no
    mantis-udi:
      build: no
    mantis-analytics:
      build:  no
    mantis-model:
      build: no
    mantis-model-generator:
      build: yes
    mantis-hadoop-clients:
      build:  yes
    mantis-hive-rest-service:
      build:  yes
    mantis-test:
      build:  no
    keytruda-prototype:  # keytruda repository
      build:  no
  enigma:  # Enigma team space
    csv2assembly:
      build: no
  svt:  # test automation tools
    dit-core:
      build:  yes
    data_integrity:
      build: yes
  mrlitsc:
    jira-utils:
      build: no
  ~kejzlar:  # Tom Kejzlar's repository
    jiragraphs:
      build:  no
    agilestats:
      build:  no
  infapfm:  # Informatica Platform repositories
    infa-bdm:
      build:  no
    informatica-monitoring:
      build:  no
    mantis:
      build:  no
    mantis-delivery:
      build:  no
    mantis-misc:
      build:  no
    mx_radar:
      build:  no
