# repositories storage for different systems
location:
  win:    c:/projects
  linux:  /home/gusevdm
  macos:  /Users/gusevdm

# general stash settings
stash:
  address:  https://gusevdm@stash.merck.com/scm/
  user:     gusevdm

proxy:
  http: 127.0.0.1:3180
  https: 127.0.0.1:3180

#https://gusevdm@stash.merck.com/scm/man/mantis-ops.git
#https://gusevdm@stash.merck.com/scm/man/mantis-pdc.git
#https://gusevdm@stash.merck.com/scm/man/mantis-hadoop-clients.git
#https://gusevdm@stash.merck.com/scm/man/mantis-hive-rest-service.git
#https://gusevdm@stash.merck.com/scm/man/mantis-model.git
#https://gusevdm@stash.merck.com/scm/man/mantis-model-generator.git
#https://gusevdm@stash.merck.com/scm/man/mantis-test.git
#https://gusevdm@stash.merck.com/scm/man/mantis-udi.git
#https://gusevdm@stash.merck.com/scm/man/mantis-bds.git
#https://gusevdm@stash.merck.com/scm/man/mantis-teradata.git
#https://gusevdm@stash.merck.com/scm/bdp/ingest-script-generator.git

repositories:
  mantis:
    key: bdp
    build: yes
  mantis11:
    key: bdp
    build: no # -> build takes too much time
  mantis-bds:
    key: man
    build: no # -> build includes python scripts, experimental
  mantis-pdc:
    key: man
    build: yes
  mantis-ops:
    key: man
    build: yes
  mantis-systems:
    key: man
    build: no # -> build includes python scripts and artifacts building
  csv2assembly:
    key: enigma
    build: no
  csv2abstract:
    key: bdp
    build: no
  csv2hive:
    key: bdp
    build: yes

# obsolete settings, will be removed
repos:
 - mantis
 - mantis11
 - mantis-bds
 - mantis-pdc
 - mantis-ops
 - mantis-systems
 - mantis-udi
 - mantis-model
 - mantis-model-generator
 - mantis-analytics
 - mantis-hadoop-clients
 - mantis-teradata
 - mantis-test
 - csv2abstract
 - csv2assembly
 - csv2hive
 - sqoop-msd
 - ingest-script-generator
 - dit-core
 - data_integrity
 - jiragraphs
# - bigdata-training
build_repos:
 - csv2abstract
 - csv2hive
 - mantis-bds
 - research
 - dit-core
