# common settings
jira_address:   https://issues.merck.com
jira_project:   Mantis
team_label:     mantis-capability
team_component: mantis-capability
team: [kaplia, zhukv, andreevi, barzilov, kudriash, iushin, gusevdm, lipkovic, gogolev, hapii]

# teams lists (all and current)
teams:
  ada_all:   [gogolev, hapii, lipkovic, kaplia, zhukv, andreevi, barzilov, kudriash, iushin, gorkoven, gusevdm, sokolose, ermolaeo]
  ada:       [kaplia, zhukv, andreevi, barzilov, kudriash, iushin, gorkoven, gusevdm]
  nova_all:  [kobiakov, listvin, sokolose, garadagl, kuchin, lukin]
  nova:      [kobiakov, listvin, garadagl, kuchin, lukin]
  bmtef_all: [iablokov, sitnikod, trukhano, gorodilo, koberd]
  bmtef:     [iablokov, sitnikod, trukhano, gorodilo, koberd]
