# yodo: fix formatting with 2 spaces (instead of 4)
version: 1
# allows to get logger on modules level (we will inherite all already defined loggers)
disable_existing_loggers: False
# patterns for log records
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    # todo: add format here
    format: "zzz"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        #level: INFO
        level: DEBUG
        formatter: simple
        filename: logs/log_info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/log_errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

# all available loggers
loggers:
    pylib:
        level: DEBUG
        #handlers: [console]
        #propagate: yes
    jirautil:
        level: DEBUG
    gitutil:
        level: DEBUG
    jira:
        level: DEBUG
    urllib3:
        level: INFO

# root logger (for all modules/scripts)
root:
  level: DEBUG
  #handlers: [console, info_file_handler, error_file_handler]
  handlers: [console]
