repos_dir: c:/projects
repos:
 - mantis
 - mantis11
 - mantis-bds
 - mantis-pdc
 - mantis-ops
 - mantis-systems
 - csv2abstract
 - csv2assembly
 - csv2hive
 - ingest-script-generator
# - bigdata-training
build_repos:
 - csv2abstract
 - csv2hive
 - mantis-bds
 - research

# - mantis11 # -> build takes too much time
# - mantis-bds # -> build includes python scripts
# - mantis-systems # -> build includes python scripts and artifacts building
