csv2hive_tool_script: bin/csv2hive-tool
csv2abstract_script: csv2abstract/rel/bin/csv2abstract
sqoop_script: sqoop-msd-bin/bin/sqoop
verify_pipeline_script: verify-pipeline/rel/bin/verify-pipeline

yarn_queue: mantis
yarn_check_interval_seconds: 10
yarn_job_info_retries: 10

webhcat_home: /usr/hdp/current/hive-webhcat
hive_client_home: /usr/hdp/current/hive-client
hadoop_client_home: /usr/hdp/current/hadoop-client

aux_hdfs_dir_base: /data/mmd
load_dttm_col: load_dttm

sqoop:
  source_system:
    oracle-11-2:
      jdbc_driver_name: oracle.jdbc.OracleDriver
      path: jdbc/ojdbc6.jar
      artifact: ojdbc6.jar
      type: FILE
    oracle-10:
      jdbc_driver_name: oracle.jdbc.OracleDriver
      path: jdbc/ojdbc14.jar
      artifact: ojdbc14.jar
      type: FILE
    mysql-15-1:
      jdbc_driver_name: com.mysql.jdbc.Driver
      path: jdbc/mysql-connector-java.jar
      artifact: mysql-connector-java.jar
      type: FILE


parsekit_settings:
  parsekit_wait_counter: 30
  parsekit_time_to_run: 60480000000
