###############################################################################
#
#   Logging config for tests with one console appender.
#
#   Created:  Dmitrii Gusev, 20.05.2019
#   Modified: Dmitrii Gusev, 24.05.2019
#
###############################################################################

version: 1
disable_existing_loggers: False  # allows to get logger on modules level
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

loggers:
    gitupdate:
        level: DEBUG
        #handlers: [console]

# root logger
root:
    level: DEBUG
    handlers: [console]
