package edu.dmgusev;

/** This Java source file was generated by the Gradle 'init' task. */

public class SimpleApplication {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new SimpleApplication().getGreeting());
    }

}
