###############################################################################
#
#   Logging configuration file for Fleet Scraper Component.
#
#   Created:  Dmitrii Gusev, 2020
#   Modified: Dmitrii Gusev, 29.04.2021
#
###############################################################################

version: 1
# allows to get logger on modules level
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    std_file_handler:
        class: logging.handlers.RotatingFileHandler
        #level: INFO
        level: DEBUG
        formatter: simple
        filename: logs/log_info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/log_errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

# all available loggers
loggers:
    pylib:
        level:  DEBUG
        #handlers: [console]
        #propagate: yes
    scraper_utilities:         # scraper utilities module
        level: DEBUG
    scraper_clarksonsnet:      # clarksons scraper module
        level: DEBUG
    scraper_marinetrafficcom:  # marinetraffic scraper module
        level: DEBUG
    scraper_rsclassorg:        # rs-class scraper module
        level: DEBUG
    scraper_vesselfinder:      # vessel-finder scraper module
        level: DEBUG
    fleet_scraper:             # main Fleet Scraper module
        level: DEBUG
    sqlitedb:
        level: DEBUG

# root logger
root:
    level: INFO
    handlers: [console, std_file_handler, error_file_handler]  # will be inherited by other loggers
