[tool.poetry]
name = "ansible-edu"
version = "0.1.0"
description = ""
authors = ["Dmitrii Gusev <dmitry.ed.gusev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
