/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.dmgusev;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

/** Test class for the simple auto-generated application. */

class SimpleApplicationTest {

    @Test
    void appHasAGreeting() {
        SimpleApplication classUnderTest = new SimpleApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

}
