# LuxMS server environment (local, development)
luxms_env_local:
  #lux_url:      http://192.168.0.178/api
  lux_url:      http://192.168.72.128/api
  lux_user:     admin
  lux_password: admin

# LuxMS server environment (virtual, development/test/debug)
luxms_env_virtual:
  lux_url:      http://192.168.72.128/api
  lux_user:     admin
  lux_password: admin

# LuxMS server environment (production)
#luxms_env_prod:
#  lux_url:      http://192.168.72.128/api
#  lux_user:     admin
#  lux_password: admin

# DataTex environment (local, development)
datatex_env_local:
  db_host:   127.0.0.1
  db_port:   1521
  db_user:   user
  db_pass:   pass
  db_schema: schema

# DataTex environment (virtual, development/test/debug)
datatex_env_virtual:
  db_host:   127.0.0.1
  db_port:   1521
  db_user:   user
  db_pass:   pass
  db_schema: NOW4

# DataTex environment (production)
#datatex_env_prod:
#  db_host:   127.0.0.1
#  db_port:   1521
#  db_user:   user
#  db_pass:   pass
#  db_schema: schema

# general options
general_env:
  # directory for export CSV files (could be absolute/relative)
  csv_directory: csv_export
